development:
  adapter: mysql
  encoding: utf8
  database: dvd_catalog;
  pool: 5
  username : gaba
  password: 'gabita'
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: dvd_catalog_test;
  pool: 5
  username : gaba
  password: 'gabita'
  socket: /tmp/mysql.sock
